import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { Screen } from '@/components/ui/Screen';
import { lessons } from '@/data/mock';
import { colors } from '@/theme/colors';

const sectionIcon = { theory: 'book-outline', audio: 'headset-outline', video: 'play-circle-outline', practice: 'extension-puzzle-outline', quiz: 'checkmark-circle-outline' } as const;

export default function LessonDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const lesson = lessons.find((item) => item.id === id);
  if (!lesson) return <Screen><Text>Dars topilmadi.</Text></Screen>;
  return <Screen><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={21} color={colors.text} /></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>{lesson.number}-DARS</Text><Text style={styles.title}>{lesson.title}</Text></View></View><Text style={styles.description}>{lesson.description}</Text><View style={styles.progress}><View style={styles.progressTop}><Text style={styles.progressLabel}>Dars progressi</Text><Text style={styles.progressValue}>{lesson.progress}%</Text></View><ProgressBar value={lesson.progress} /></View><View style={styles.list}>{lesson.sections.map((section, index) => <Pressable key={section.id} style={styles.section}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><Ionicons name={sectionIcon[section.type]} size={22} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.sectionTitle}>{section.title}</Text><Text style={styles.sectionText}>{section.description}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></Pressable>)}</View><Pressable style={styles.cta}><Text style={styles.ctaText}>{lesson.progress > 0 ? 'Darsni davom ettirish' : 'Darsni boshlash'}</Text></Pressable><Text style={styles.note}>Keyingi milestone’da real audio, video, mashq va testlar backenddan ulanadi.</Text></Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, eyebrow: { color: colors.primary, fontSize: 11, fontWeight: '900' }, title: { fontSize: 26, fontWeight: '900', color: colors.text }, description: { fontSize: 15, lineHeight: 22, color: colors.muted }, progress: { gap: 9, backgroundColor: colors.surface, padding: 16, borderRadius: 20, borderWidth: 1, borderColor: colors.border }, progressTop: { flexDirection: 'row', justifyContent: 'space-between' }, progressLabel: { fontSize: 13, fontWeight: '700', color: colors.text }, progressValue: { fontSize: 13, fontWeight: '900', color: colors.primary }, list: { gap: 10 }, section: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderRadius: 20, padding: 14, borderWidth: 1, borderColor: colors.border }, number: { width: 28, height: 28, borderRadius: 10, backgroundColor: '#EEF2FF', alignItems: 'center', justifyContent: 'center' }, numberText: { color: colors.primary, fontWeight: '900' }, sectionTitle: { color: colors.text, fontSize: 15, fontWeight: '800' }, sectionText: { color: colors.muted, fontSize: 12, lineHeight: 17 }, cta: { height: 56, borderRadius: 18, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, ctaText: { color: '#fff', fontWeight: '800' }, note: { color: colors.muted, fontSize: 12, textAlign: 'center' } });
